# This file generates the GitHub Actions matrix
---

# Board and shield matrix:
board:
  - nice_nano
shield:
  - cradio_left
  - cradio_right

# Additional builds outside of the above matrix:
include:
  - board: tipper_tf
