

# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing

points:
  zones:
    matrix:
      columns:
        outer:
          rows.bottom.skip: true
        pinky.key.stagger: 0.4U
        ring.key:
          stagger: 0.7U
        middle.key.stagger: 0.25U
        index.key.stagger: -0.25U
        inner.key.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.66U, -1.25U]
        rotate: -10
      columns:
        tucky:
          key.name: thumb_tucky
        reachy:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          key.name: thumb_reachy

outlines:
  pcb:
    - what: rectangle
      where: true
      asym: source
      size: 23
      corner: 1
  plate:
    - what: rectangle
      where: true
      asym: source
      size: 18
      corner: 3
    - what: rectangle
      where: true
      asym: source
      size: 14
      bound: false
      operation: subtract
  pcb_perimeter_raw:
    - what: rectangle
      where: true
      asym: source
      size: 21
      corner: 1
  polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: matrix_pinky_bottom
          shift: [-9,-9]
        - ref: matrix_pinky_home
          shift: [-9,1.3u]
        - ref: matrix_middle_home
          shift: [-9,9]
        - ref: matrix_middle_home
          shift: [9,9]
        - ref: matrix_index_home
          shift: [1.45u,9]
        - ref: thumb_reachy
          shift: [8,-9]
        - ref: thumb_tucky
          shift: [9,-9]
  pcb_perimeter:
    - what: outline # keys
      name: pcb_perimeter_raw
    - what: outline
      name: polygon
      operation: add
pcbs:
  trone:
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      keys:
        what: mx
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reverse: true
          keycaps: true
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [21,-32]
          rotate: -90


